raml:
  container_name: raml
  build: .
  command: /usr/bin/gulp --path raml-files/chasqui/index.raml
  volumes:
    - ./raml-files:/usr/local/app/raml-files
    - ./docs:/usr/local/app/docs
  ports:
    - "3000:3000"
